name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run test suite
      id: run-test-suite
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Run test suite
        setup-command: python -m pip install --upgrade pip; pip install flask; pip
          install psycopg2; curl -o ProductionCode/psql_config.py https://anyaevostinar.github.io/classes/257-s25/psql_config.py
        command: python3 -m unittest discover -s Tests
        timeout: 10
    - name: Coverage report
      id: coverage-report
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Coverage report
        setup-command: python -m pip install --upgrade pip; pip install coverage;
          pip install flask; pip install psycopg2; curl -o ProductionCode/psql_config.py
          https://anyaevostinar.github.io/classes/257-s25/psql_config.py
        command: python3 -m coverage run --source ProductionCode,app,cl -m unittest
          discover Tests; python3 -m coverage report -m
        timeout: 10
    - name: Style check - Production Code
      id: style-check-production-code
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Style check - Production Code
        setup-command: python -m pip install --upgrade pip; pip install pylint
        command: pylint --disable=import-error ProductionCode
        timeout: 10
    - name: Style check - Tests
      id: style-check-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Style check - Tests
        setup-command: python -m pip install --upgrade pip; pip install pylint
        command: pylint --disable=import-error,arguments-differ Tests
        timeout: 10
    - name: Style check - cl
      id: style-check-cl
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Style check - cl
        setup-command: python -m pip install --upgrade pip; pip install pylint
        command: pylint --disable=import-error cl.py
        timeout: 10
    - name: Style check - app
      id: style-check-app
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Style check - app
        setup-command: python -m pip install --upgrade pip; pip install pylint
        command: pylint --disable=import-error --score=y app.py
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUN-TEST-SUITE_RESULTS: "${{steps.run-test-suite.outputs.result}}"
        COVERAGE-REPORT_RESULTS: "${{steps.coverage-report.outputs.result}}"
        STYLE-CHECK-PRODUCTION-CODE_RESULTS: "${{steps.style-check-production-code.outputs.result}}"
        STYLE-CHECK-TESTS_RESULTS: "${{steps.style-check-tests.outputs.result}}"
        STYLE-CHECK-CL_RESULTS: "${{steps.style-check-cl.outputs.result}}"
        STYLE-CHECK-APP_RESULTS: "${{steps.style-check-app.outputs.result}}"
      with:
        runners: run-test-suite,coverage-report,style-check-production-code,style-check-tests,style-check-cl,style-check-app
